<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDPi5t4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDPi5t4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMDPi5t4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMDPi5t4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMDPi5t4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MDPi5t4',
    'container.build_id' => '13d87233',
    'container.build_time' => 1539765946,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDPi5t4');
